google-modules: soc: Fix setting policy limits when frequency tables are used [1/3]
Subsequent to 15888cd ("cpufreq: Fix setting policy limits when frequency tables are used")

This resolves the following compilation error:

../google-modules/soc/gs/drivers/cpufreq/exynos-acme.c: In function 'dm_scaler':
../google-modules/soc/gs/drivers/cpufreq/exynos-acme.c:1013:24: error: too few arguments to function 'cpufreq_frequency_table_target'
 1013 |         target_index = cpufreq_frequency_table_target(policy, target_freq, relation);
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../google-modules/soc/gs/drivers/cpufreq/exynos-acme.c:19:
../include/linux/cpufreq.h:1064:19: note: declared here
 1064 | static inline int cpufreq_frequency_table_target(struct cpufreq_policy *policy,
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Adam W. Willis <return.of.octobot@gmail.com>