tensor_aio: Fix setting policy limits when frequency tables are used [3/3]
Subsequent to 15888cd ("cpufreq: Fix setting policy limits when frequency tables are used")

This resolves the following compilation errors:

../drivers/devfreq/tensor_aio.c: In function 'find_cpu_freq':
../drivers/devfreq/tensor_aio.c:781:15: error: too few arguments to function 'cpufreq_frequency_table_target'
  781 |         idx = cpufreq_frequency_table_target(pol, khz, relation);
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../drivers/devfreq/tensor_aio.c:6:
../include/linux/cpufreq.h:1064:19: note: declared here
 1064 | static inline int cpufreq_frequency_table_target(struct cpufreq_policy *policy,
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../drivers/devfreq/tensor_aio.c: At top level:
../drivers/devfreq/tensor_aio.c:1437:19: error: conflicting types for 'find_index_l'; have 'u32(struct exynos_devfreq_data *, u32)' {aka 'unsigned int(struct exynos_devfreq_data *, unsigned int)'}
 1437 | static inline u32 find_index_l(struct exynos_devfreq_data *data, u32 target)
      |                   ^~~~~~~~~~~~
../include/linux/cpufreq.h:858:19: note: previous definition of 'find_index_l' with type 'int(struct cpufreq_policy *, unsigned int,  unsigned int,  unsigned int,  bool)' {aka 'int(struct cpufreq_policy *, unsigned int,  unsigned int,  unsigned int,  _Bool)'}
  858 | static inline int find_index_l(struct cpufreq_policy *policy,
      |                   ^~~~~~~~~~~~

[@0ctobot: Additionally, prefix find_index_l to avoid function collision]
Signed-off-by: Adam W. Willis <return.of.octobot@gmail.com>